### ISSUE TITLE
Please code with surface reflectance of landsat 5/7

### ISSUE THREAD

**Issue by HafezAhmad** [sofiaermida/Landsat_SMW_LST#3]
Thank you so much creating this. I am trying to use landsat 7 with l7 with your script.This is not giving lst properly
TIR BT: Layer error: Image.select: Pattern 'B10' did not match any bands.
Image.select: Pattern 'B10' did not match any bands.

**Comment by sofiaermida** [comment]
The code uses the correct bands automatically but you need to update Map.addLayer() code on example_1.js. The band names are available on Landsat_LST.js.
