### ISSUE TITLE
Update git repo using collection 2 data

### ISSUE THREAD

**Issue by luanabeckerdaluz** [sofiaermida/Landsat_SMW_LST#4]
Hi Sofia,

Just to warn that the code was updated on 11/07/2022 on the GEE directory using Collection 2 data but this GitHub repo hasn't been updated yet. 

The **new code** can be accessed in **_[https://earthengine.googlesource.com/users/sofiaermida/landsat_smw_lst](https://earthengine.googlesource.com/users/sofiaermida/landsat_smw_lst.)_**

Thank you!

Regards,
Leonardo

**Comment by sofiaermida** [comment]
Ah yes, thank you for reminding me!
