### ISSUE TITLE
Code not working for whole year

### ISSUE THREAD

**Issue by Muhammad-Waqas5012** [sofiaermida/Landsat_SMW_LST#6]
The code is not working, I tried to run example 1 for Islamabad, the capital of Pakistan for the years 2010 and 2020 but the code is not working. Screenshot attached. The code is showing the upper region but not working for Rawalpindi and Islamabad

![Screenshot_1](https://user-images.githubusercontent.com/104750476/216818575-99968023-a4ad-43fa-89ab-6b44e2d8f03b.jpg)

**Comment by sofiaermida** [comment]
The exmaple 1 only shows one random image. It is possible that that image does not cover the full region. For a better representation I would suggest averaging all the images in the collection. Please see the GEE tutorials on how to do this.
