### ISSUE TITLE
Question about "NaN"

### ISSUE THREAD

**Issue by Simpson-bart** [sofiaermida/Landsat_SMW_LST#7]
Thank you very much for your sharing. As a novice, i have a question about why did part of the "NaN" appear after the temperature inversion after calling your code for my own research area.
Maybe there is  some parameter I need to modify?
![image](https://user-images.githubusercontent.com/132647850/236397436-f82adfb0-624d-4047-9541-e3fab12e99c1.png)
Study area: Hangzhou City, Zhejiang Province, China, 118°21′E-120°30′E，29°11′N-30°33′N

**Comment by sofiaermida** [comment]
The NAN means that one of the inputs does not have data.
