### ISSUE TITLE
Landsat 9

### ISSUE THREAD

**Issue by YanCheng-go** [sofiaermida/Landsat_SMW_LST#8]
Hi sofia, are you planning to include landsat 9 as well in the near future?

**Comment by sofiaermida** [comment]
I'm planning to but the Landsat 9 RTTOV coefficients are not available yet. I need them to recalibrate the coefficients.

**Comment by crendl** [comment]
dear sofia, 
is there by chance an update on the missing coefficients?

obrigado

**Comment by sofiaermida** [comment]
The code is now running for Landsat 9.
