### ISSUE TITLE
should cloud masking be enabled by default?

### ISSUE THREAD

**Issue by mgalbright** [sofiaermida/Landsat_SMW_LST#9]
Quick question: It looks like cloud masking is disabled for TOA calculations - see [line 120](https://github.com/sofiaermida/Landsat_SMW_LST/blob/65fd1ae9c752b6e3f738405495bcb1b5c773cf4d/modules/Landsat_LST.js#L120). 

Shouldn't cloud masking be enabled (by default) for TOA, like it is for SR? [line 127](https://github.com/sofiaermida/Landsat_SMW_LST/blob/65fd1ae9c752b6e3f738405495bcb1b5c773cf4d/modules/Landsat_LST.js#L127)

**Comment by sofiaermida** [comment]
It can be but because the algorithm needs the SR data, if the SR data is masked then the final LST will also be masked. So masking the TOA data is redundant.
